import 'package:whatsapp_clone/features/updates/models/status/status_cards_model.dart';

final List<StatusCardsModel> cardsList = [
  StatusCardsModel(
    name: "John Smith",
    topicTitle: "Flutter Basics",
    description: "Introduction to Flutter widgets and layouts.",
    city: "Lahore",
    date: "2025-08-01",
    time: "10:30 AM",
  ),
  StatusCardsModel(
    name: "Emily Johnson",
    topicTitle: "State Management",
    description: "Understanding Riverpod and Provider in Flutter.",
    city: "Karachi",
    date: "2025-08-02",
    time: "02:00 PM",
  ),
  StatusCardsModel(
    name: "Michael Brown",
    topicTitle: "Networking in Flutter",
    description: "Making API calls with Dio and Retrofit.",
    city: "Islamabad",
    date: "2025-08-03",
    time: "09:00 AM",
  ),
  StatusCardsModel(
    name: "Sophia Davis",
    topicTitle: "Flutter Animations",
    description: "Learn implicit and explicit animations.",
    city: "Multan",
    date: "2025-08-04",
    time: "01:15 PM",
  ),
  StatusCardsModel(
    name: "Daniel Wilson",
    topicTitle: "Clean Architecture",
    description: "Implementing domain-driven design in Flutter.",
    city: "Rawalpindi",
    date: "2025-08-05",
    time: "11:45 AM",
  ),
  StatusCardsModel(
    name: "Olivia Taylor",
    topicTitle: "Flutter UI Design",
    description: "Building responsive UIs with best practices.",
    city: "Faisalabad",
    date: "2025-08-06",
    time: "03:30 PM",
  ),
  StatusCardsModel(
    name: "James Anderson",
    topicTitle: "Testing in Flutter",
    description: "Unit testing, widget testing, and integration tests.",
    city: "Peshawar",
    date: "2025-08-07",
    time: "04:20 PM",
  ),
  StatusCardsModel(
    name: "Isabella Thomas",
    topicTitle: "Flutter for Web",
    description: "Deploying and optimizing Flutter web apps.",
    city: "Quetta",
    date: "2025-08-08",
    time: "12:10 PM",
  ),
  StatusCardsModel(
    name: "Benjamin Martinez",
    topicTitle: "Firebase Integration",
    description: "Authentication, Firestore, and cloud messaging.",
    city: "Hyderabad",
    date: "2025-08-09",
    time: "09:50 AM",
  ),
  StatusCardsModel(
    name: "Mia Garcia",
    topicTitle: "Advanced Flutter Widgets",
    description: "Deep dive into CustomPainter and Slivers.",
    city: "Sialkot",
    date: "2025-08-10",
    time: "05:00 PM",
  ),
];
