import 'package:hanging_around_wd_ui/features/updates/models/channels/channel_model.dart';

final List<ChannelModel> channelsList = [
  ChannelModel(
    channelName: "Flutter Devs",
    description: "Discuss Flutter updates and issues",
    date: "2025-07-28",
    newMessages: 12,
    link: true,
  ),
  ChannelModel(
    channelName: "Tech Talks",
    description: "Latest news in tech world",
    date: "2025-07-27",
    newMessages: 5,
    link: true,
  ),
  ChannelModel(
    channelName: "UI/UX Design",
    description: "Tips for modern UI/UX design",
    date: "2025-07-26",
    newMessages: 0,
    image: true,
  ),
  ChannelModel(
    channelName: "Gaming Zone",
    description: "Share new games and reviews",
    date: "2025-07-28",
    newMessages: 9,
    video: true,
  ),
  ChannelModel(
    channelName: "Travel Buddies",
    description: "Plan your next adventure",
    date: "2025-07-24",
    newMessages: 1,
  ),
  ChannelModel(
    channelName: "Book Club",
    description: "Discuss books and recommendations",
    date: "2025-07-29",
    newMessages: 7,
  ),
  ChannelModel(
    channelName: "Healthy Living",
    description: "Fitness and nutrition tips",
    date: "2025-07-28",
    newMessages: 2,
    link: true,
  ),
  ChannelModel(
    channelName: "Startup Founders",
    description: "Business and startup growth discussions",
    date: "2025-07-23",
    newMessages: 4,
    image: true,
  ),
  ChannelModel(
    channelName: "Movie Lovers",
    description: "Latest movies and reviews",
    date: "2025-07-26",
    newMessages: 3,
    video: true,
  ),
  ChannelModel(
    channelName: "Photography",
    description: "Share your best shots and tutorials",
    date: "2025-07-27",
    newMessages: 8,
  ),
  ChannelModel(
    channelName: "Crypto Chat",
    description: "Discuss crypto market trends",
    date: "2025-07-25",
    newMessages: 11,
  ),
  ChannelModel(
    channelName: "Music Vibes",
    description: "Share playlists and music news",
    date: "2025-07-28",
    newMessages: 6,
    image: true,
  ),
  ChannelModel(
    channelName: "Coding Masters",
    description: "Discuss programming challenges",
    date: "2025-07-29",
    newMessages: 10,
    image: true,
  ),
  ChannelModel(
    channelName: "Fashion Trends",
    description: "Latest fashion and style guides",
    date: "2025-07-27",
    newMessages: 3,
  ),
  ChannelModel(
    channelName: "Foodies",
    description: "Recipes and restaurant reviews",
    date: "2025-07-24",
    newMessages: 2,
    video: true,
  ),
  ChannelModel(
    channelName: "Science Hub",
    description: "Explore new science discoveries",
    date: "2025-07-22",
    newMessages: 7,
    link: true,
  ),
  ChannelModel(
    channelName: "AI & ML",
    description: "Machine learning and AI talks",
    date: "2025-07-26",
    newMessages: 5,
  ),
  ChannelModel(
    channelName: "Language Learners",
    description: "Tips for learning new languages",
    date: "2025-07-28",
    newMessages: 1,
    link: true,
  ),
  ChannelModel(
    channelName: "Parenting Guide",
    description: "Support for parents and families",
    date: "2025-07-23",
    newMessages: 0,
  ),
  ChannelModel(
    channelName: "Sports Talk",
    description: "Discuss sports events and news",
    date: "2025-07-29",
    newMessages: 9,
    image: true,
  ),
];
