import 'package:hanging_around_wd_ui/features/chats/model/chats_model.dart';

final List<ChatsModel> users = [
  ChatsModel(
    imageUrl: "https://randomuser.me/api/portraits/men/1.jpg",
    name: "John Smith",
    message: "Hey, how are you doing today?",
    time: "09:12 AM",
    currentStatus: 'Groups',
    sentAndRecieved: true,
    seen: true,
  ),
  ChatsModel(
    imageUrl: "https://randomuser.me/api/portraits/women/2.jpg",
    name: "Emily Johnson",
    message: "Let's meet at the coffee shop later.",
    time: "10:45 AM",
    currentStatus: 'Favourites',
    sentAndRecieved: true,
    seen: true,
  ),
  ChatsModel(
    imageUrl: "https://randomuser.me/api/portraits/men/3.jpg",
    name: "Michael Brown",
    message: "Got the documents you sent me.",
    time: "11:20 AM",
    currentStatus: 'Unread',
    sentAndRecieved: true,
    seen: false,
  ),
  ChatsModel(
    imageUrl: "https://randomuser.me/api/portraits/women/4.jpg",
    name: "Sophia Davis",
    message: "Can't talk right now, call you later.",
    time: "12:10 PM",
    currentStatus: 'Groups',
    sentAndRecieved: false,
    seen: false,
  ),
  ChatsModel(
    imageUrl: "https://randomuser.me/api/portraits/men/5.jpg",
    name: "Daniel Wilson",
    message: "Happy birthday! Wish you all the best.",
    time: "01:05 PM",
    currentStatus: 'Favourites',
    sentAndRecieved: true,
    seen: true,
  ),
  ChatsModel(
    imageUrl: "https://randomuser.me/api/portraits/women/6.jpg",
    name: "Olivia Taylor",
    message: "Where are you? Been waiting outside.",
    time: "02:40 PM",
    currentStatus: 'Groups',
    sentAndRecieved: false,
    seen: false,
  ),
  ChatsModel(
    imageUrl: "https://randomuser.me/api/portraits/men/7.jpg",
    name: "Rachel Green",
    message: "I love fashion job it's my dream job.",
    time: "10:55 PM",
    currentStatus: 'Pinned',
    sentAndRecieved: false,
    seen: false,
  ),
  ChatsModel(
    imageUrl: "https://randomuser.me/api/portraits/men/7.jpg",
    name: "Ross Geller",
    message: "How are you Rach, could you do me a favour?",
    time: "03:55 PM",
    currentStatus: 'Groups',
    sentAndRecieved: true,
    seen: false,
  ),
  ChatsModel(
    imageUrl: "https://randomuser.me/api/portraits/men/7.jpg",
    name: "James Anderson",
    message: "Sure, let's do it this weekend.",
    time: "03:55 PM",
    currentStatus: 'Communities',
    sentAndRecieved: true,
    seen: true,
  ),
  ChatsModel(
    imageUrl: "https://randomuser.me/api/portraits/men/7.jpg",
    name: "Phoebe Buffay",
    message: "I love my brother I wanna give a big surprise.",
    time: "03:40 PM",
    currentStatus: 'Favourites',
    sentAndRecieved: true,
    seen: false,
  ),
  ChatsModel(
    imageUrl: "https://randomuser.me/api/portraits/men/7.jpg",
    name: "Joey Tribbiani",
    message: "I order 2 Dozens sandwiches :)",
    time: "11:05 PM",
    currentStatus: 'Communities',
    sentAndRecieved: true,
    seen: false,
  ),
  ChatsModel(
    imageUrl: "https://randomuser.me/api/portraits/men/7.jpg",
    name: "Monica Geller",
    message: "Please empty that trash.",
    time: "05:21 PM",
    currentStatus: 'Favourites',
    sentAndRecieved: true,
    seen: true,
  ),
  ChatsModel(
    imageUrl: "https://randomuser.me/api/portraits/men/7.jpg",
    name: "Danny Morsan",
    message: "You hair style is differet bro.",
    time: "08:33 PM",
    currentStatus: 'Unread',
    sentAndRecieved: true,
    seen: false,
  ),
  ChatsModel(
    imageUrl: "https://randomuser.me/api/portraits/women/8.jpg",
    name: "Isabella Thomas",
    message: "Had a great time last night, thanks!",
    time: "04:30 PM",
    currentStatus: 'Communities',
    sentAndRecieved: true,
    seen: true,
  ),
  ChatsModel(
    imageUrl: "https://randomuser.me/api/portraits/men/9.jpg",
    name: "Benjamin Martinez",
    message: "Check out the new project files.",
    time: "05:20 PM",
    currentStatus: 'Communities',
    sentAndRecieved: false,
    seen: false,
  ),
  ChatsModel(
    imageUrl: "https://randomuser.me/api/portraits/women/10.jpg",
    name: "Mia Garcia",
    message: "Will you join the call tomorrow?",
    time: "06:15 PM",
    currentStatus: 'Groups',
    sentAndRecieved: true,
    seen: false,
  ),
  ChatsModel(
    imageUrl: "https://randomuser.me/api/portraits/men/11.jpg",
    name: "William Lee",
    message: "Let's finalize the report by Friday.",
    time: "07:00 PM",
    currentStatus: 'Pinned',
    sentAndRecieved: true,
    seen: true,
  ),
  ChatsModel(
    imageUrl: "https://randomuser.me/api/portraits/women/12.jpg",
    name: "Charlotte Harris",
    message: "Sent you the location on WhatsApp.",
    time: "07:45 PM",
    currentStatus: 'Communities',
    sentAndRecieved: false,
    seen: false,
  ),
  ChatsModel(
    imageUrl: "https://randomuser.me/api/portraits/men/13.jpg",
    name: "Ethan Clark",
    message: "Sure, I'll bring the documents with me.",
    time: "08:30 PM",
    currentStatus: 'Pinned',
    sentAndRecieved: true,
    seen: true,
  ),
  ChatsModel(
    imageUrl: "https://randomuser.me/api/portraits/women/14.jpg",
    name: "Amelia Lewis",
    message: "Did you check the new restaurant?",
    time: "09:10 PM",
    currentStatus: 'Communities',
    sentAndRecieved: true,
    seen: false,
  ),
  ChatsModel(
    imageUrl: "https://randomuser.me/api/portraits/men/15.jpg",
    name: "Alexander Robinson",
    message: "Let’s catch up after office hours.",
    time: "09:50 PM",
    currentStatus: 'Groups',
    sentAndRecieved: true,
    seen: false,
  ),
  ChatsModel(
    imageUrl: "https://randomuser.me/api/portraits/women/16.jpg",
    name: "Harper Walker",
    message: "Great job on the presentation!",
    time: "10:20 PM",
    currentStatus: 'Pinned',
    sentAndRecieved: true,
    seen: true,
  ),
  ChatsModel(
    imageUrl: "https://randomuser.me/api/portraits/men/17.jpg",
    name: "Jacob Young",
    message: "✅Please review the contract updates.",
    time: "11:05 PM",
    currentStatus: 'Unread',
    sentAndRecieved: true,
    seen: true,
  ),
  ChatsModel(
    imageUrl: "https://randomuser.me/api/portraits/women/18.jpg",
    name: "Evelyn King",
    message: "I'll send the package tomorrow morning.",
    time: "11:40 PM",
    currentStatus: 'Unread',
    sentAndRecieved: false,
    seen: false,
  ),
  ChatsModel(
    imageUrl: "https://randomuser.me/api/portraits/men/19.jpg",
    name: "Henry Wright",
    message: "Meeting postponed to next Tuesday.",
    time: "Yesterday",
    currentStatus: 'Communities',
    sentAndRecieved: false,
    seen: false,
  ),
  ChatsModel(
    imageUrl: "https://randomuser.me/api/portraits/women/20.jpg",
    name: "Abigail Scott",
    message: "We won yesterday game.",
    time: "6 days ago",
    currentStatus: 'Pinned',
    sentAndRecieved: true,
    seen: false,
  ),
  ChatsModel(
    imageUrl: "https://randomuser.me/api/portraits/women/20.jpg",
    name: "Belly Bucher",
    message: "Need help with the design mockups.",
    time: "2 days ago",
    currentStatus: 'Groups',
    sentAndRecieved: true,
    seen: false,
  ),
  ChatsModel(
    imageUrl: "https://randomuser.me/api/portraits/women/20.jpg",
    name: "Harlay Adkins",
    message: "Need help with the design mockups.",
    time: "2 days ago",
    currentStatus: 'Pinned',
    sentAndRecieved: false,
    seen: false,
  ),
  ChatsModel(
    imageUrl: "https://randomuser.me/api/portraits/women/20.jpg",
    name: "Chandler Bing",
    message: "Do you need me on Saturday.",
    time: "5 days ago",
    currentStatus: 'Communities',
    sentAndRecieved: true,
    seen: false,
  ),
  ChatsModel(
    imageUrl: "https://randomuser.me/api/portraits/women/20.jpg",
    name: "Samules Geller",
    message: "GReat to hear that.",
    time: "2 days ago",
    currentStatus: 'Favourites',
    sentAndRecieved: false,
    seen: false,
  ),
  ChatsModel(
    imageUrl: "https://randomuser.me/api/portraits/women/20.jpg",
    name: "Abigail Scott",
    message: "Need help with the design mockups.",
    time: "2 days ago",
    currentStatus: 'Unread',
    sentAndRecieved: true,
    seen: true,
  ),
];
